# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'NewsDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
   use_frameworks!
   pod 'AFNetworking'
   pod 'SVProgressHUD', '~> 2.0.3’
   pod 'WMPageController'
   pod 'Masonry'
   pod 'MJRefresh'
   pod 'SDCycleScrollView'
   pod 'ZFPlayer', '~> 3.0'
   pod 'ZFPlayer/ControlView', '~> 3.0'
   pod 'ZFPlayer/AVPlayer', '~> 3.0'
   pod 'YYModel'
   pod 'DZNEmptyDataSet'
   pod 'UMengAnalytics-NO-IDFA', '~> 4.2.5'
   pod 'IQKeyboardManager'
   pod 'TMUserCenter'
   
  # Pods for NewsDemo

end
